//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/celsius_to_farhenheit", ReplyAction="*")]
        double celsius_to_farhenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/celsius_to_farhenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> celsius_to_farhenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/farhenheit_to_celsius", ReplyAction="*")]
        double farhenheit_to_celsius(double farhenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/farhenheit_to_celsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> farhenheit_to_celsiusAsync(double farhenheit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Temp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Temp.ServiceReference1.WebService1Soap>, Temp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double celsius_to_farhenheit(double celsius) {
            return base.Channel.celsius_to_farhenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<double> celsius_to_farhenheitAsync(double celsius) {
            return base.Channel.celsius_to_farhenheitAsync(celsius);
        }
        
        public double farhenheit_to_celsius(double farhenheit) {
            return base.Channel.farhenheit_to_celsius(farhenheit);
        }
        
        public System.Threading.Tasks.Task<double> farhenheit_to_celsiusAsync(double farhenheit) {
            return base.Channel.farhenheit_to_celsiusAsync(farhenheit);
        }
    }
}
